-- Title: Clantags
-- Script ID: 145
-- Source: page_145.html
----------------------------------------

--[[
 _   _                 _     _____           _                 
| \ | |               | |   /  ___|         | |                
|  \| |_   _  __ _ ___| |__ \ `--. _   _ ___| |_ ___ _ __ ___  
| . ` | | | |/ _` / __| '_ \ `--. \ | | / __| __/ _ \ '_ ` _ \ 
| |\  | |_| | (_| \__ \ | | /\__/ / |_| \__ \ ||  __/ | | | | |
\_| \_/\__, |\__,_|___/_| |_\____/ \__, |___/\__\___|_| |_| |_|
        __/ |                       __/ |                      
       |___/                       |___/                       
]]



local main_Hrisitosense = {
    " ",
    "| ",
    "|- ",
    "|-| ",
    "H ",
    "H^ ",
    "Hr ",
    "Hr1 ",
    "Hri ",
    "Hri$ ",
    "Hris1 ",
    "Hrisi ",
    "HrisiT ",
    "Hrisit ",
    "Hrisit0 ",
    "Hrisit0_ ",
    "Hrisito ",
    "Hrisito$ ",
    "Hrisitos ",
    "Hrisitos3 ",
    "Hrisitose ",
    "Hrisitose| ",
    "Hrisitose|\\ ",
    "Hrisitose|\\| ",
    "Hrisitosen ",
    "Hrisitosen$ ",
    "Hrisitosens ",
    "Hrisitosens3 ",
    "Hrisitosense ",
    "Hrisitosens3 ",
    "Hrisitosens ",
    "Hrisitosen$ ",
    "Hrisitosen ",
    "Hrisitose|\\| ",
    "Hrisitose|\\ ",
    "Hrisitose| ",
    "Hrisitose ",
    "Hrisitos3 ",
    "Hrisitos ",
    "Hrisito$ ",
    "Hrisito ",
    "Hrisit0 ",
    "Hrisit ",
    "HrisiT ",
    "Hrisi ",
    "Hris1 ",
    "Hri$ ",
    "Hr1 ",
    "Hr ",
    "H^ ",
    "H ",
    "|-| ",
    "|- ",
    "| ",
    " ",
}

local main_MonkeySquad = {
    ">",
    ">M",
    ">Mo",
    ">Mon",
    ">Monk",
    ">Monke",
    ">Monkey",
    ">Monkey",
    ">MonkeyS",
    ">MonkeySq",
    ">MonkeySqu",
    ">MonkeySqua",
    ">MonkeySquad",
    "MonkeySquad",
    "$onkeySquad",
    "M$nkeySquad",
    "Mo$keySquad",
    "Mon$eySquad",
    "Monk$ySquad",
    "Monke$Squad",
    "Monkey$quad",
    "MonkeyS$uad",
    "MonkeySq$ad",
    "MonkeySqu$d",
    "MonkeySqua$",
    "MonkeySquad",
    "MonkeySqua<",
    "MonkeySqu<",
    "MonkeySq<",
    "MonkeyS<",
    "Monkey<",
    "Monke<",
    "Monk<",
    "Mon<",
    "Mo<",
    "M<",
    "<",
}
local main_BosniaHook = {
    "☂",
    "☂B",
    "☂Bo",
    "☂Bos",
    "☂Bosn",
    "☂Bosni",
    "☂Bosnia",
    "☂BosniaH",
    "☂BosniaHo",
    "☂BosniaHoo",
    "☂BosniaHook",
    "B☂osniaHook",
    "Bo☂sniaHook",
    "Bos☂niaHook",
    "Bosn☂iaHook",
    "Bosni☂aHook",                   
    "Bosnia☂Hook",
    "BosniaH☂ook",
    "BosniaHo☂ok",
    "BosniaHoo☂k",
    "BosniaHook☂",
    "BosniaHook",       
    "BosniaHook",
    "BosniaHook",
    "_osniaHoo_",
    "__sniaHo__",
    "___niaH___",
    "____ia____",
    "__________",
    "_____",
    "__", 
    "_",
    "",             
    "☂",
}
local main_ev0lve = {
    "           ",
    "         e" ,
    "        ev" ,
    "       ev0" ,
    "      ev0l" ,
    "     ev0lv" ,
    "    ev0lve" ,
    "   ev0lve." ,
    "  ev0lve.x ",
    " ev0lve.xy ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " ev0lve.xyz ",
    " v0lve.xyz " ,
    " 0lve.xyz ",
    " lve.xyz ",
    "ve.xyz   ",
    "e.xyz    ",
    ".xyz     ",
    "xyz      ",
    "yz       ",
    "z        ",
}
local main_primordial = {
    " ⌛ ",
    " ⌛ ",
    " ⌛ ",
    " ⌛ p ",
    " ⌛ pr ",
    " ⌛ pri ",
    " ⌛ prim ",
    " ⌛ primo ",
    " ⌛ primor ",
    " ⌛ primord ",
    " ⌛ primordi ",
    " ⌛ primordia ",
    " ⌛ primordial ",
    " ⌛ primordial ",
    " ⌛ primordia ",
    " ⌛ primordi ",
    " ⌛ primord ",
    " ⌛ primor ",
    " ⌛ primo ",
    " ⌛ prim ",
    " ⌛ pri ",
    " ⌛ pr ",
    " ⌛ p ",
}
local main_Rawetrip = {
    " 〄 " ,
    " R>|〄 " ,
    " RA>|〄 " ,
    " R4W>|〄 " ,
    " RAWЭ>|〄 " ,
    " R4W3T>|〄 " ,
    " RAWΣTR>|〄 " ,
    " Я4WETRI>|〄 " ,
    " RAWETRIP>|〄 " ,
    " RAWETRIP<|〄 " ,
    " R4WETRI<|〄 " ,
    " RAWΣTR<|〄 " ,
    " R4W3T<|〄 " ,
    " RAWЭ<|〄 " ,
    " R4W<|〄 " ,
    " RA<|〄 " ,
    " R<|〄 " ,
    " 〄 " ,
}
local main_Neverlose = {
    " ",
    "N ",
    "N3 ",
    "Ne ",
    "Ne\\ ",
    "Ne\\/ ",
    "Nev ",
    "Nev3 ",
    "Neve ",
    "Neve| ",
    "Neve|2 ",
    "Never| ",
    "Never|_ ",
    "Neverl ",
    "Neverl0 ",
    "Neverlo ",
    "Neverlo5 ",
    "Neverlos ",
    "Neverlos3 ",
    "Neverlose ",
    "Neverlose. ",
    "Neverlose.< ",
    "Neverlose.c< ",
    "Neverlose.cc ",
    "Neverlose.c< ",
    "Neverlose.< ",
    "Neverlose. ",
    "Neverlose ",
    "Neverlos3 ",
    "Neverlos ",
    "Neverlo_ ",
    "Neverlo5 ",
    "Neverlo ",
    "Neverl_ ",
    "Never|0 ",
    "Never| ",
    "Neve|2 ",
    "Neve| ",
    "Neve ",
    "Nev3 ",
    "Nev ",
    "Ne\\/ ",
    "Ne\\ ",
    "Ne ",
    "N3 ",
    "N ",
    "|\\| ",
}
local main_Gamesense = {
    "                  ",
    "                 g",
    "                ga",
    "               gam",
    "              game",
    "             games",
    "            gamese",
    "           gamesen",
    "          gamesens",
    "         gamesense",
    "        gamesense ",
    "       gamesense  ",
    "      gamesense   ",
    "     gamesense    ",
    "    gamesense     ",
    "   gamesense      ",
    "  gamesense       ",
    " gamesense        ",
    "gamesense         ",
    "amesense          ",
    "mesense           ",
    "esense            ",
    "sense             ",
    "sens              ",
    "sen               ",
    "se                ",
    "s                 ",
}
local main_Nemesis = {
    "nemesis",
    "n3m3sis",
    "nemesis",
    "n3m3sis",
    "nemesis",
    "n3m3sis",
    "nemesis",
    "n3m3sis",
}
local main_Onetapsu = {
    "onetap.su",
    "nepat.su o",
    "epat.su on",
    "pat.su one",
    "ap.su onet",
    "t.su oneta",
    ".su onetap",
    "su onetap.",
    "u onetap.s",
    "onetap.su",
}
local main_Monolith = {
    "[M-------] ",
    "[Mo------] ",
    "[Mon-----] ",
    "[Mono----] ",
    "[Mono----] ",
    "[Monol---] ",
    "[Monoli--] ",
    "[Monolit-] ",
    "[Monolith] ",
    "[Monolit-] ",
    "[Monoli--] ",
    "[Monol---] ",
    "[Mono----] ",
    "[Mon-----] ",
    "[Mo------] ",
    "[M-------] ",
    "[--------] ",
    "[-------<] ",
    "[------<8] ",
    "[-----<8>] ",
    "[----<8>-] ",
    "[---<8>--] ",
    "[--<8>---] ",
    "[-<8>----] ",
    "[<8>-----] ",
    "[8>------] ",
    "[>-------] ",
    "[--------] ",
}
local main_plague = {
    "plaguecheat"
}
local main_airflow = {
    "a",
    "ai",
    "air",
    "airf",
    "airfl",
    "airflo",
    "airflow",
    "airflow.",
    "airflow.s",
    "airflow.su",
    "airflow.su",
    "airflow.s",
    "airflow.",
    "airflow",
    "airflo",
    "airfl",
    "airf",
    "air",
    "ai",
    "a",
    " "
}
local main_SpiritHack = {
    "◇ ",
    "◇ ",
    "◇ S ",
    "◇ Sp ",
    "◇ Spi ",
    "◇ Spir ",
    "◇ Spirt ",
    "◇ SpirtH ",
    "◇ SpirtHa ",
    "◇ SpirtHac ",
    "◇ SpirtHack ",
    "◇ SpirtHack ",
    "◇ pirtHack ",
    "◇ irtHack ",
    "◇ rtHack ",
    "◇ tHack ",
    "◇ Hack ",
    "◇ ack ",
    "◇ ck ",
    "◇ k ",
    "◇ ",
    "◇ ",
}
local main_nixware = {
    "n",
    "ni",
    "nix",
    "nixw",
    "nixwa",
    "nixwar",
    "nixware",
    "nixware.",
    "nixware.c",
    "nixware.cc",
    "nixware.cc",
    "nixware.cc",
    "nixware.c",
    "nixware.",
    "nixware",
    "nixwar",
    "nixwa",
    "nixw",
    "nix",
    "ni",
    "n",
}
local main_aimware = {
    "AIMWARE.net",
    "t AIMWARE.ne",
    "et AIMWARE.n",
    ".net AIMWARE",
    "E.net AIMWAR",
    "RE.net AIMWA",
    "ARE.net    AIMW",
    "WARE.net AIM",
    "MWARE.net AI",
    "IMWARE.net A",
    "AIMWARE.net",
    "AIMWARE.net",
}
local main_weave = { 
    "WEAVE.SU",
    "W3AVE.SU",
    "W34VE.SU",
    "WE4V3.SU",
    "WEAV3.5U",
    "W3AV3.5U",
    "W34V3.5U",
    "&E4VE.SU",
    "$E@%^.S+",
    "$!@%^.?;",
}
local main_rifk = {
    " [ ] ",
    " [ R ] ",
    " [ Ri ] ",
    " [ Rif ] " ,
    " [ Rifk ' ] ",
    " [ Rifk ' ] ",
    " [ Rifk ' ] ",
    " [ Rifk ] ",
    " [ Rif ] ",
    " [ Ri ] ",
    " [ R ] ",
    " [ ] ",
}
local main_legendware = {
    "l ",
    "le ",
    "leg ",
    "lege ",
    "legen ",
    "legend ",
    "legendw ",
    "legendwa ",
    "legendwar ",
    "legendware ",
    "legendware ",
    "legendwar ",
    "legendwa ",
    "legendw ",
    "legend ",
    "legen " ,
    "lege ",
    "leg ",
    "le ",
    "l ",
}
local main_millionware = {
    "$ millionware ",
    "$ e millionwar",
    "$ re millionwa",
    "$ are millionw",
    "$ ware million",
    "$ nware millio",
    "$ onware milli",
    "$ ionware mill",
    "$ lionware mil",
    "$ llionware mi",
    "$ illionware m",
    "$ millionware" ,
}
local main_skeetcc = {
    " s",
    " sk",
    " ske",
    " skee",
    " skee.",
    " skeet.",
    " skeet.c",
    " skeet.cc",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.cc ",
    " skeet.c ",
    " skeet. ",
    " skeet ",
    " skee ",
    " ske ",
    " sk ",
    " s ",
    "  ",
    " ",
}
local main_nineelevel = {
    "✈__▮_▮ ",
    "_✈_▮_▮",
    "__✈▮_▮",
    "___☠✈▮",
    "___☠_☠ ",
}

local tags = {
    MonkeySquad = main_Rifk,
    BosniaHook = main_BosniaHook,
    Ev0lve = main_ev0lve,
    Primordial = main_primordial,
    RaweTrip = main_Rawetrip,
    Neverlose = main_Neverlose,
    Gamesense = main_Gamesense,
    Skeetcc = main_skeetcc,
    Nemesis = main_Nemesis,
    Onetapsu = main_Onetapsu,
    Monolith = main_Monolith,
    Airflow = main_airflow,
    PlagueCheat = main_plague,
    SpiritHack = main_SpiritHack,
    Legendware = main_legendware,
    Nixware = main_nixware,
    Aimware = main_aimware,
    Weave = main_weave,
    Rifk = main_Rifk,
    Hrisitosense = main_Hrisitosense
}


local clantag_custom = ui.new_checkbox("LUA", "A", "Clantag")
local clantag_cheats = ui.new_combobox("LUA","A","Cheats Clantags", {"Hrisitosense","MonkeySquad","BosniaHook","Ev0lve","Primordial","RaweTrip","Neverlose","Gamesense","Skeet.cc","Nemesis","Onetap.su","Monolith","Airflow","PlagueCheat","SpiritHack","Legendware","Nixware","Aimware","Weave","Rifk"})
ui.set_visible(clantag_cheats, false)

local clantagc_index = 1
local lastc_time = globals.realtime()

local function setc_clantag(tag)
    client.set_clan_tag(tag)
end

local function update_clantagc()
    local selectedc_clantag = ui.get(clantag_cheats)
    if selectedc_clantag == "-" then return end
    
    local tag_list = tags[selectedc_clantag]
    if not tag_list or #tag_list == 0 then return end

    if globals.realtime() - lastc_time >= 0.2 then
        setc_clantag(tag_list[clantagc_index])
        clantagc_index = clantagc_index + 1

        if clantagc_index > #tag_list then
            clantagc_index = 1
        end

        lastc_time = globals.realtime()
    end
end

local function toggle_clantag_ui()
    local enabled = ui.get(clantag_custom)
    ui.set_visible(clantag_cheats, enabled)
end

ui.set_callback(clantag_custom, toggle_clantag_ui)
client.set_event_callback("paint", update_clantagc)-- dumped from hrisito forums by <youtube.com/@subtick> ~ rip hrisito 2025-2026
